# -*- coding: utf-8 -*-
"""Scamdetector2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1z1OpwUqsD2w6BcoIPuMHeQeRgN9BLaIa
"""

!pip install SpeechRecognition pydub

!apt-get install -y portaudio19-dev

!pip install PyAudio

#!/usr/bin/env python3
"""
Challenge 1 – Real-Time AI Scam Call Detection
LIVE MIC + RECORDED AUDIO ANALYSIS (Multilingual Support)
"""

import sys
import os
from collections import deque
import speech_recognition as sr
from pydub import AudioSegment

class ScamCallDetector:
    def __init__(self):
        # Multilingual keywords (English + translations)
        self.scam_keywords = {
            "en-IN": {"otp", "bank", "account", "verify", "urgent", "police", "kbc", "lottery", "refund", "kyc", "suspend", "arrest", "press"},
            "hi-IN": {"ओटीपी", "बैंक", "खाता", "सत्यापित", "तत्काल", "पुलिस", "केबीसी", "लॉटरी", "रिफंड", "केवाईसी", "निलंबित", "गिरफ्तार", "दबाएं"},  # Hindi
            "te-IN": {"ఓటిపి", "బ్యాంక్", "ఖాతా", "ధృవీకరించు", "తత్కాల", "పోలీస్", "కెబిసి", "లాటరీ", "రిఫండ్", "కెవైసి", "నిలిపివేయు", "అరెస్ట్", "ప్రెస్"},  # Telugu
            "ta-IN": {"ஓடிபி", "வங்கி", "கணக்கு", "சரிபார்க்க", "அவசரம்", "காவல்துறை", "கேபிசி", "லாட்டரி", "திரும்பப்பெறு", "கேவைசி", "நிறுத்து", "கைது", "அழுத்து"},  # Tamil
            "ml-IN": {"ഓടിപി", "ബാങ്ക്", "അക്കൗണ്ട്", "പരിശോധിക്കുക", "അടിയന്തരം", "പോലീസ്", "കെബിസി", "ലോട്ടറി", "റിഫണ്ട്", "കെവൈസി", "നിർത്തുക", "അറസ്റ്റ്", "അമർത്തുക"}  # Malayalam
        }

        self.authority_words = {
            "en-IN": {"police", "bank", "government", "court"},
            "hi-IN": {"पुलिस", "बैंक", "सरकार", "कोर्ट"},
            "te-IN": {"పోలీస్", "బ్యాంక్", "ప్రభుత్వం", "కోర్ట్"},
            "ta-IN": {"காவல்துறை", "வங்கி", "அரசு", "நீதிமன்றம்"},
            "ml-IN": {"പോലീസ്", "ബാങ്ക്", "സർക്കാർ", "കോടതി"}
        }

        self.urgency_phrases = {
            "en-IN": {"urgent", "immediately", "right now", "as soon as possible"},
            "hi-IN": {"तत्काल", "तुरंत", "अभी", "जितनी जल्दी हो सके"},
            "te-IN": {"తత్కాల", "వెంటనే", "ఇప్పుడు", "వీలైనంత త్వరగా"},
            "ta-IN": {"அவசரம்", "உடனே", "இப்போது", "முடிந்தவரை விரைவாக"},
            "ml-IN": {"അടിയന്തരം", "ഉടനെ", "ഇപ്പോൾ", "സാധ്യമായത്ര വേഗം"}
        }

        self.current_score = 0
        self.detected_keywords = set()
        self.transcript_buffer = deque(maxlen=10)

        self.recognizer = sr.Recognizer()
        self.separator = "-" * 45

    def classify_risk(self):
        if self.current_score >= 7:
            return "FRAUD"
        elif self.current_score >= 4:
            return "SUSPICIOUS"
        return "SAFE"

    def evaluate_text(self, text, language):
        text = text.lower()
        score = 0

        keywords = self.scam_keywords.get(language, self.scam_keywords["en-IN"])
        authorities = self.authority_words.get(language, self.authority_words["en-IN"])
        urgencies = self.urgency_phrases.get(language, self.urgency_phrases["en-IN"])

        for word in text.split():
            if word in keywords and word not in self.detected_keywords:
                score += 2
                self.detected_keywords.add(word)

        for word in authorities:
            if word in text:
                score += 3

        for phrase in urgencies:
            if phrase in text:
                score += 2

        self.current_score += score

    def print_status(self, text, language):
        self.evaluate_text(text, language)
        print(f"Transcript: {text}")
        print(f"Risk Score: {self.current_score}")
        print(f"Status: {self.classify_risk()}")
        print(self.separator)

    # ================= LIVE MICROPHONE MODE =================

    def start_live_call(self, language):
        print(f"\nINCOMING CALL: Unknown Number (Language: {language})")
        print(" Live listening started (Ctrl+C to stop)")
        print(self.separator)

        with sr.Microphone() as source:
            self.recognizer.adjust_for_ambient_noise(source)

            while True:
                try:
                    audio = self.recognizer.listen(source, timeout=5)
                    text = self.recognizer.recognize_google(audio, language=language)
                    self.transcript_buffer.append(text)
                    self.print_status(text, language)

                except sr.WaitTimeoutError:
                    continue
                except sr.UnknownValueError:
                    continue
                except sr.RequestError as e:
                    print(f"Speech service error: {e}. Check API limits or try again later.")
                    break
                except KeyboardInterrupt:
                    print("\n📞 Call Ended")
                    break

    # ================= RECORDED AUDIO MODE =================

    def analyze_recorded_call(self, file_path, language):
        if not os.path.exists(file_path):
            print(" Audio file not found.")
            return

        print(f"\nRECORDED CALL ANALYSIS (Language: {language})")
        print(self.separator)

        try:
            audio = AudioSegment.from_file(file_path)
            if len(audio) == 0:
                print("Audio file is empty or invalid.")
                return
            audio.export("temp.wav", format="wav")
        except Exception as e:
            print(f"Error processing audio file: {e}")
            return

        with sr.AudioFile("temp.wav") as source:
            audio_data = self.recognizer.record(source)

        try:
            text = self.recognizer.recognize_google(audio_data, language=language)
        except sr.UnknownValueError:
            print("No speech detected.")
            return
        except sr.RequestError as e:
            print(f"Speech service error: {e}. Possible causes: API quota exceeded, invalid audio, or network issues. Try a shorter file or use an API key.")
            return

        print(f"Transcript: {text}")
        print(self.separator)

        self.evaluate_text(text, language)

        print("FINAL RESULT")
        print(f"Risk Score: {self.current_score}")
        print(f"Classification: {self.classify_risk()}")
        print(self.separator)

        if os.path.exists("temp.wav"):
            os.remove("temp.wav")

def main():
    detector = ScamCallDetector()

    print("\nCHOOSE LANGUAGE")
    print("1 → English (en-IN)")
    print("2 → Hindi (hi-IN)")
    print("3 → Telugu (te-IN)")
    print("4 → Tamil (ta-IN)")
    print("5 → Malayalam (ml-IN)")
    lang_choice = input("Enter language choice (1-5): ").strip()

    language_map = {
        "1": "en-IN",
        "2": "hi-IN",
        "3": "te-IN",
        "4": "ta-IN",
        "5": "ml-IN"
    }
    language = language_map.get(lang_choice, "en-IN")  # Default to English

    print("\nCHOOSE MODE")
    print("1 → Live Call Detection (Microphone)")
    print("2 → Recorded Call Analysis (Audio File)")
    choice = input("Enter choice (1/2): ").strip()

    if choice == "1":
        detector.start_live_call(language)

    elif choice == "2":
        path = input("Enter path to .wav audio file: ").strip()
        detector.analyze_recorded_call(path, language)

    else:
        print("Invalid choice.")

if __name__ == "__main__":
    main()